config/routes.rb
Requate2::Application.routes.draw do
  devise_for :users
  root :to => "pages#index"
  resources :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :notifiers
  has_many :memberships
  has_many :users, through: :memberships
  has_many :payments
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/notifier.rb
class Notifier < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  after_create :notify_group

  def notify_group
    group.users.each{|u| u.notify_of_payment(self)}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notifiers
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @group = Group.new
  end

  def create
    current_user.groups << Group.create(group_params)
    redirect_to groups_path
  end

  def index
    @groups = current_user.groups
  end

  def show
    @group = current_user.groups.find(params[:id])
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_nav_signed_in.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Requate", root_url %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#"><%= current_user.email %></a>
        <ul class="dropdown">
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><a href="#">Settings</a></li>
          <li class="alert"><%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: 'button alert' %></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li class="has-dropdown">
        <%= link_to "Groups", groups_path %>
        <ul class="dropdown">
          <% current_user.groups.each do |group| %>
            <li><%= link_to group.name, group_path(group) %></li>
          <% end %>
          <li><%= link_to "+ Group", new_group_path, class: 'button success' %></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/application/_nav_signed_out.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Requate", root_url %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to "Sign In", new_user_session_path, class: 'button' %></li>
      <li><%= link_to "Sign Up", new_user_registration_path, class: 'button success' %></li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      
    </ul>
  </section>
</nav>

app/views/groups/index.html.erb
<h1>Groups<h1>

<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group_path(group) %></li>
  <% end %>

  <li><%= link_to "+Group", new_group_path %></li>
</ul>

app/views/groups/new.html.erb
<%= form_for @group, url: {action: "create"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create", class: 'button' %>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<ul>
  <% @group.users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Requate" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'nav_signed_in' %>
    <% else %>
      <%= render 'nav_signed_out' %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="row">
      <div class="small-9 small-centered columns"><%= yield %></div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/index.html.erb
Index